services:
  - type: web
    name: app-builder-api
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
