services:
  - type: web
    name: app-builder-api
    env: python
      # Avoid requiring Playwright browsers to be installed on Render.com.
      # Playwright-related browser installs (chromium) are removed so the service
      # can build without downloading a browser. The evaluation code will detect
      # if Playwright/browsers are available and fall back to an HTTP-based
      # checker when necessary.
    buildCommand: pip install -r requirements.txt
    # Use the equals form so the port value is passed as part of the option
    # token (avoids CLI parsing issues in some shells):
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port=$PORT
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
        # Optional: if you want Playwright with browsers on Render, set
        # PLAYWRIGHT_BROWSERS_PATH and install browsers during build (not required).